In [1]:
#importar a biblioteca
import numpy as np

In [2]:
#posso criar um array apartir de uma lista!
#criando listas
qtde = [2, 5, 10, 20, 35]
custo = [100, 150, 450, 320, 195]

In [3]:
#Transformando a lista "qtd" em array, utilizando o numpy e chamando a função array
arr1 = np.array(qtde)

In [4]:
arr2 = np.array(custo)

In [5]:
#Quando eu tento multiplicar listas, recebo o "TypeError: can´t multiply sequence by non-int of type list", 
#isso significa que não posso multiplicar listas.

estoque = qtde*custo

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
#Quando faço a mesma operação, mas agora utilizando array, 
estoque1 = arr1*arr2

In [11]:
estoque1

array([ 200,  750, 4500, 6400, 6825])

In [12]:
custo1 = [100, 200, 300, 400]
venda = [125, 235, 355, 490]

In [13]:
arr3 = np.array(custo1)
arr4 = np.array(venda)

In [14]:
lucro = arr4 - arr3

In [15]:
lucro

array([25, 35, 55, 90])

In [ ]:
#Criando arrays através do numpy
#1ºmétodo: arange

In [17]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
#posso especificar o salto que desejo
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [19]:
#Posso especificar o tipo de dado que eu quero também.
np.arange(10,21,2,dtype = float)

array([10., 12., 14., 16., 18., 20.])

In [ ]:
#2ºmétodo:Linspace retorna números espaçados de modo uniforme em um intervalo. 
#Dessa forma, dado um ponto inicial e de parada, assim como a quantidade de valores, linspace irá distribuí-los 
#uniformemente para você em uma matriz NumPy. 
#Isso é especialmente útil para visualizações de dados e declaração de eixos durante a plotagem.

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])